#!/bin/bash


echo $1 $2 $3

script=none
if [[ $1 == "example" ]]; then
    script=./etc/scripts/STARTRUN.example
elif [[ $1 == "testrpi" ]]; then
    script=./sandbox/STARTRUN
elif [[ $1 == "rpi" ]]; then
    script=./producers/cmshgcal/STARTRUN_RPI
elif [[ $1 == "cmshgcal" ]]; then
    script=./producers/cmshgcal/STARTRUN
elif [[ $1 == "dwc" ]]; then
    script=./producers/cmshgcal/STARTRUN_DWC
else
    # default
    script=./sandbox/STARTRUN
fi

ln -s $script tmp.start

./tmp.start

rm ./tmp.start
