#!/bin/bash

#source ~/opt/root/6.08.04/build/bin/thisroot.sh

#source build_env.sh

printf '\033[1;32;48m \t STARTING DAQ LOCALLY\033[0m \n'
echo $(date)
printf '\033[22;33m\t Cleaning up first...  \033[0m \n'

if [ -f KILLRUN.local ]
then
    sh KILLRUN.local
else
    sh KILLRUN
fi

printf '\033[22;31m\t End of killall \033[0m \n'

sleep 1

######################################################################
#if [ -n "`ls data/run*.raw`" ]
#then
#    printf '\033[22;33m\t Making sure all data files are properly writeprotected \033[0m \n'
#    chmod a=rw data/run*.raw
#    printf '\033[22;32m\t ...Done!\033[0m \n'
#fi

#cd $DATADIR/data
EUDAQBIN=./

cd bin 

#=====================================================================
printf '\033[22;33m\t Starting Subprocesses \033[0m \n'
#=====================================================================
######################################################################
# euRun
###############
printf '\033[22;33m\t RunControl \033[0m \n'
$EUDAQBIN/euRun.exe -x 0 -y 0 -w 650 -g 550 -a tcp://$RCPORT &
sleep 1

######################################################################
# euLog
###############
printf '\033[22;33m\t Logger  \033[0m \n'
$EUDAQBIN/euLog.exe -x 0 -y 550 -w 1500 -g 450 -r tcp://$HOSTIP:44000 | tee --append ../log/EULOG.txt &
sleep 2

######################################################################
# DataCollector
###############
printf '\033[22;33m\t caliceDataCollector \033[0m \n'
#xterm -sb -sl 1000 -geom 80x10-480-900 -fn fixed -T "Data Collector" -e "./caliceDataCollector -r tcp://$HOSTIP:$RCPORT" &
#$CALEUDAQ/caliceDataCollector -n CaliceDataCollector -r tcp://$HOSTIP:$RCPORT &
xterm -sb -sl 100000 -geom 80x10-480-900 -fn fixed -T "Data Collector" -e "./TestDataCollector.exe -r tcp://$HOSTIP:$RCPORT 2>&1 | tee ../logs/DataCollector.log && read ||read" &
#./caliceDataCollector -r tcp://$HOSTIP:$RCPORT" &
#./TestDataCollector.exe -r tcp://$HOSTIP:$RCPORT > $flog 2>&1 &
sleep 3

#######################################################################
# OnlineMonitor
####################
#xterm -sb -sl 10000 -T "ONLINE Monitor" -e "./OnlineMon.exe  -sc 10 -s 0 -tc 0 -r tcp://$HOSTIP:$RCPORT &&read||read" &
xterm -sb -sl 10000 -T "ONLINE Monitor" -e "./OnlineMon.exe  -sc 1 -s 0 -tc 0 -r tcp://$HOSTIP:$RCPORT &&read||read" &
sleep 2


#######################################################################
# AHCAL producer
####################
printf '\033[22;33m\t  caliceProducer-scintillator  \033[0m \n'
xterm -sb -sl 1000000 -geom 160x10-480-900 -fn fixed -T "CALICE AHCAL" -e "./AHCALProducer.exe -n CaliceSc -r tcp://$TLUIP:$RCPORT && read || read" & 
#./AHCALProducer.exe -n CaliceSc -r tcp://$TLUIP:$RCPORT 


printf ' \n'
printf ' \n'
printf ' \n'
printf '\033[1;32;48m\t ...Done!\033[0m \n'
printf '\033[1;32;48mSTART OF DAQ COMPLETE\033[0m \n'
